# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AI stuff
email: jeblad@google.com
description: >- # this means to ignore newlines until "baseurl:"
  The site describes various aspects of AI technology, and what works and what not. It will
  not always support mainstream ideas.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jeblad.github.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Authors
authors :
  jeblad:
    name : John Erling Blad
    email : jeblad@gmail.com
    github : jeblad
    twitter : jeblad
    keybase : jeblad
    linkedin : jeblad
    wikimedia : jeblad
    about: >-
      I am a computer scientist, with a cand. sci. in mathematical modelling of analog processors
      for neuromorph audio processing. In other words how to localize sound sources by using an
      analog computer with transistors in low inversion. Very cool, and very weird. That was back
      then, when the neural net field was new, and people still belived analog processing was the
      way to go. Since then most funding has dried up, and I do web programming as most other
      people in IT-science. But the way to go is still analog processing, it is just the rest of
      the world does not know it.

# Build settings
markdown: kramdown
theme: jekyll-materialdocs
remote_theme: chromatical/jekyll-materialdocs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-avatar

# Favicons, etc
logo : /assets/icons/logo-small.png

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
